name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :kmvn-frontend:jsBrowserDevelopmentExecutableDistribution
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: "kmvnrepo"
          apiToken: ${{ secrets.CF_API_TOKEN }}
          directory: kmvn-frontend/build/dist/js/developmentExecutable/
          gitHubToken: ${{ secrets.GH_TOKEN }}